apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: docker.io/bitnami/odoo:16
          ports: 
            - containerPort: 8069
          resources:
            requests:
              cpu: 300m
              memory: 200Mi
            limits:
              cpu: 600m
              memory: 400Mi
          env:
            - name: ODOO_DATABASE_PASSWORD
              value: "k8smaestro"
            - name: ODOO_DATABASE_NAME
              value: "k8smaestro"
            - name: ODOO_DATABASE_USER
              value: "odoo"
            - name: ODOO_DATABASE_PORT_NUMBER
              value: "5432"
            - name: ODOO_DATABASE_HOST
              value: "postgresql.odoo.svc.cluster.local"
