apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
spec:
  selector:
    matchLabels:
      app: busybox-payment
  replicas: 2
  template:
    metadata:
      labels:
        app: busybox-payment
    spec:
      containers:
        - name: busybox-payment
          image: busybox:1.36.0
          command:
          - sh
          - -c
          - |
            echo "MERCHANT_ID: $MERCHANT_ID"
            echo "PAYMENT_GATEWAY_API_KEY: $PAYMENT_GATEWAY_API_KEY"
          env: 
            - name: MERCHANT_ID
              valueFrom:
                configMapKeyRef:
                  name: payment-configmap
                  key: MARCHANT_ID
            - name: PAYMENT_GATEWAY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: api_key
